server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:freiraumbande}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

security:
  jwt:
    issuer: "freiraumbande"
    accessTtlMinutes: 1440
    secret: ${JWT_SECRET}